services:
  lico-resident:
    build:
      context: ../../..
      dockerfile: packages/lico-devc/.devcontainer/Dockerfile
    volumes:
      - ../../..:/workspace:cached
    stdin_open: true
    tty: true
