default-severity: error

extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-config-prettier

plugins:
  - stylelint-prettier

rules:
  declaration-block-no-duplicate-properties: true
  unit-no-unknown: true
  property-no-vendor-prefix: true
  value-no-vendor-prefix: true
  block-no-empty: true
  max-nesting-depth: 3
  max-line-length: 79
  prettier/prettier: true

overrides:
  - files: ["**/*.html"]
    customSyntax: postcss-html
