[environment]
extra-paths = [
  "packages/lico-backup/src",
  "packages/lico-config/src",
  "packages/lico-devc/src",
  "packages/lico-exec/src",
  "packages/lico-lint/src",
  "packages/lico-log/src",
  "packages/lico-logger/src",
  "packages/lico-memory/src",
  "packages/lico-pipeline/src",
  "packages/lico-shim/src",
]
python-version = "3.14"

[src]
include = [
  "packages/lico-backup/src",
  "packages/lico-backup/tests",
  "packages/lico-config/src",
  "packages/lico-config/tests",
  "packages/lico-devc/src",
  "packages/lico-devc/tests",
  "packages/lico-exec/src",
  "packages/lico-exec/tests",
  "packages/lico-lint/src",
  "packages/lico-lint/tests",
  "packages/lico-log/src",
  "packages/lico-log/tests",
  "packages/lico-logger/src",
  "packages/lico-logger/tests",
  "packages/lico-memory/src",
  "packages/lico-memory/tests",
  "packages/lico-pipeline/src",
  "packages/lico-pipeline/tests",
  "packages/lico-shim/src",
  "packages/lico-shim/tests",
]
exclude = [
  "**/.venv",
  "**/.temp",
  "**/.trash",
  "**/node_modules",
  "**/__pycache__",
  "**/.agent/.internal/archive",
  "**/.human/.internal/archive",
  "**/.repos/.licoshdw/archive",
]

[rules]
unknown-parameter-type = "error"
unknown-argument-type = "error"
unknown-variable-type = "error"
unknown-member-access = "error"
unknown-return-type = "error"
report-missing-imports = "error"
possibly-unbound-attribute = "error"
redundant-cast = "error"
unused-ignore = "error"
deprecated = "error"
